title: Natalie Widmann
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description...
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tilana.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: Natalie Widmann # add your name
author-img: profile-pic2.png # add your photo
about-author: NLP & ML specialist - excited about technology & society # add description
social-twitter: tilana145 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: tilana # add your Github handle
social-linkedin: natalie-widmann-5241191aa/ # add your Linkedin handle
social-email: natalie_widmann@posteo.net# add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
